import { Info, AlertTriangle, BookOpen, Code, Globe2, Shield, Users } from 'lucide-react';

export default function About() {
  return (
    <div className="space-y-6 animate-fade-in max-w-4xl">
      <div>
        <h2 className="text-xl font-bold text-slate-900">About CYCLONE-AI</h2>
        <p className="text-sm text-slate-600 mt-1">Multi-Source AI Platform for Tropical Cyclone Intelligence</p>
      </div>

      <div className="bg-white shadow-sm border-slate-200 rounded-xl border border-slate-200 p-6">
        <h3 className="text-lg font-semibold text-slate-900 mb-2">SIH Problem Statement</h3>
        <div className="space-y-2 text-sm text-slate-500">
          <p><strong className="text-blue-600">ID:</strong> 26070</p>
          <p><strong className="text-blue-600">Title:</strong> AI/ML-based system for identification, classification, and prediction of tropical cyclone patterns using multi-source satellite data</p>
          <p><strong className="text-blue-600">Organization:</strong> Ministry of Earth Sciences (MoES)</p>
          <p><strong className="text-blue-600">Department:</strong> India Meteorological Department (IMD)</p>
          <p><strong className="text-blue-600">Theme:</strong> Disaster Management</p>
        </div>
      </div>

      <div className="bg-white shadow-sm border-slate-200 rounded-xl border border-slate-200 p-6">
        <h3 className="text-base font-semibold text-slate-900 mb-3 flex items-center gap-2"><Globe2 className="w-5 h-5 text-cyan-600" />System Capabilities</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm text-slate-500">
          {[
            'Tropical cyclone detection from satellite imagery',
            'Cyclone center localization via CNN regression',
            'IMD-compatible cyclone stage classification',
            'Maximum sustained wind estimation',
            'Minimum central pressure estimation',
            'Multi-horizon track forecasting (+6/12/24/48h)',
            'Rapid intensification detection',
            'Monte Carlo dropout uncertainty estimation',
            'Grad-CAM explainability for satellite analysis',
            'Permutation-based feature importance',
            'Rules-based risk assessment engine',
            'Configurable alert system',
            'Interactive Leaflet cyclone track visualization',
            'Historical cyclone analysis',
            'Multi-source dataset support (IBTrACS, TCIR, ERA5)',
            'Model performance tracking and versioning',
          ].map((cap, i) => (
            <div key={i} className="flex items-start gap-2">
              <span className="text-cyan-600 mt-0.5">•</span>
              <span>{cap}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-white shadow-sm border-slate-200 rounded-xl border border-slate-200 p-6">
        <h3 className="text-base font-semibold text-slate-900 mb-3 flex items-center gap-2"><Code className="w-5 h-5 text-blue-600" />Technology Stack</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div><h4 className="text-blue-600 font-medium mb-1">Frontend</h4><p className="text-slate-600">React • TypeScript • Vite • Tailwind CSS • Leaflet • Recharts</p></div>
          <div><h4 className="text-blue-600 font-medium mb-1">Backend</h4><p className="text-slate-600">Python • FastAPI • SQLAlchemy • Pydantic • Uvicorn</p></div>
          <div><h4 className="text-blue-600 font-medium mb-1">AI/ML</h4><p className="text-slate-600">PyTorch • CNN • LSTM • MLP • Grad-CAM • MC Dropout</p></div>
          <div><h4 className="text-blue-600 font-medium mb-1">Data</h4><p className="text-slate-600">IBTrACS • TCIR • ERA5 • GPM IMERG • SQLite/PostgreSQL</p></div>
        </div>
      </div>

      <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-6">
        <h3 className="text-base font-semibold text-amber-600 mb-3 flex items-center gap-2">
          <AlertTriangle className="w-5 h-5" /> Important Disclaimers
        </h3>
        <div className="space-y-2 text-sm text-amber-300/80">
          <p>• This is an <strong>AI decision-support research prototype</strong>, NOT an official warning system.</p>
          <p>• All predictions are generated by baseline ML models and should not be used for operational decision-making.</p>
          <p>• This system must not replace official advisories issued by the India Meteorological Department (IMD) or other authorized agencies.</p>
          <p>• Demo data is synthetic and does not represent real observations.</p>
          <p>• Model uncertainty estimates are derived from Monte Carlo dropout and are not scientifically validated confidence intervals.</p>
          <p>• AI predictions can be wrong. Disaster management decisions require human expertise and official guidance.</p>
        </div>
      </div>

      <div className="bg-white shadow-sm border-slate-200 rounded-xl border border-slate-200 p-6">
        <h3 className="text-base font-semibold text-slate-900 mb-3 flex items-center gap-2"><Shield className="w-5 h-5 text-green-600" />Ethical Considerations</h3>
        <div className="space-y-2 text-sm text-slate-500">
          <p>• Vulnerable populations must not be unfairly deprioritized in disaster response decisions.</p>
          <p>• Model biases from historical data must be monitored and documented.</p>
          <p>• Uncertainty must always be communicated alongside predictions.</p>
          <p>• Official meteorological agencies remain the authoritative source for cyclone warnings.</p>
        </div>
      </div>
    </div>
  );
}
